plugin_configuration:
  ConnectionString: "SERVER=127.0.0.1;PORT=3306;DATABASE=unturned;UID=root;PASSWORD=admin"
  TableName: "UniversalModeration"
  BanWebHookURL: "URL HERE"
  KickWebHookURL: "URL HERE"